# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions
# More info on Python, GitHub Actions, and Azure App Service: https://aka.ms/python-webapps-actions

name: (Production) Build and deploy Python app to Azure Web App Challenge PI

on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  DB_SERVER: ${{ secrets.DB_SERVER }}'
  DB_PORT: ${{ secrets.DB_PORT }}'
  DB_UID: '${{ secrets.DB_UID }}'
  DB_PASS: '${{ secrets.DB_PASS }}'
  DB_NAME: '${{ secrets.DB_NAME }}'
  OPENAI_TYPE: '${{ secrets.OPENAI_TYPE }}'
  OPENAI_VERSION: '${{ secrets.OPENAI_VERSION }}'
  OPENAI_KEY: '${{ secrets.OPENAI_KEY }}'
  OPENAI_BASE: '${{ secrets.OPENAI_BASE }}'
  CHAT_GPT_DEPLOYMENT: '${{ secrets.CHAT_GPT_DEPLOYMENT }}'
  CHAT_GPT_MAX_CONTENT: '${{ secrets.CHAT_GPT_MAX_CONTENT }}'
  CHAT_GPT_REGION: '${{ secrets.CHAT_GPT_REGION }}'
  CHAT_GPT_URL: '${{ secrets.CHAT_GPT_URL }}'
  CHAT_GTP_KEY: '${{ secrets.CHAT_GTP_KEY }}'
  JWT_SECRET: '${{ secrets.JWT_SECRET }}'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python version
        uses: actions/setup-python@v1
        with:
          python-version: '3.10'

      - name: Create and start virtual environment
        run: |
          python -m venv venv
          source venv/bin/activate
      
      - name: Install dependencies
        run: pip install -r requirements.txt
        
      # Optional: Add step to run tests here (PyTest, Django test suites, etc.)

      - name: Zip artifact for deployment
        run: zip release.zip ./* -r

      - name: Upload artifact for deployment jobs
        uses: actions/upload-artifact@v3
        with:
          name: python-app
          path: |
            release.zip
            !venv/

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    
    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v3
        with:
          name: python-app

      - name: Unzip artifact for deployment
        run: unzip release.zip

      
      - name: 'Deploy to Azure Web App'
        uses: azure/webapps-deploy@v2
        id: deploy-to-webapp
        with:
          app-name: 'app-tutelas-eastus-prod'
          slot-name: 'Production'
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_PROD }}